### ISSUE TITLE
zend math required for csrf validation - not in require or suggest

### ISSUE THREAD

**Issue by nclundsten** [zendframework/zend-form#195]
re composer.json

requires zend-validator, but no way to bring in zend math from zend-form package, as its only "suggested"

any way to fix this? or should i just require zend math in my apps composer.json?

**Comment by froschdesign** [comment]
> requires zend-validator

Right and zend-validator's `composer.json` includes:

```json
"suggest": {
    "zendframework/zend-math": "Zend\\Math component, required by the Csrf validator",
}
```

https://github.com/zendframework/zend-validator/blob/87e743d11d49a157011a49a962c25e7a11adc7c5/composer.json#L38

**Comment by nclundsten** [comment]
Yes, but thats 2 levels deep of suggests, just to get a part of zend form
working.. this is intended??

**Comment by froschdesign** [comment]
@nclundsten 
zend-form doesn't need zend-math, but zend-validator. The same like PHPUnit and Xdebug extension or Guzzle and PSR Log.
This is the normal behavior with dependencies when dealing with Composer.

**Comment by nclundsten** [comment]
Ok, thanks, ill just require zend math in my apps composer json :)

**Comment by froschdesign** [comment]
> ill just require zend math in my apps composer json

If you need the Csrf validator! :wi

**Comment by Ocramius** [comment]
We could probably figure out if `Zend\Math` can be dropped from
dependencies since PHP 7.2 now has ext-sodium

On 27 Feb 2018 07:16, "Frank Brückner" <notifications@github.com> wrote:

@nclundsten <https://github.com/nclundsten>
zend-form doesn't need zend-math, but zend-validator. The same like PHPUnit
and Xdebug extension or Guzzle and PSR Log.
This is the normal behavior with dependencies when dealing with Composer.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zendframework/zend-form/issues/195#issuecomment-368759713>,
or mute the thread

**Comment by froschdesign** [comment]
@Ocramius 
Good point!
