### ISSUE TITLE
Standalone library

### ISSUE THREAD

**Issue by Mech7** [zendframework/zend-form#6]
The form component does not really work as standalone library atleast the rendering see:
For the viewhelpers you need 
zend-view, for zend-view you need zend-servicemanager for zend-servicemanager you need zend-i18n, for zend-i18n you need zend-escaper. :(
But all of them are not listed as required dependencies.

**Comment by manuakasam** [comment]
This is just the nature of web-forms.

The dependencies are not required because you don't need them for all use-cases. For example you're perfectly capable of extending Form functionality by only extending zend-form components. You won't need any of the rendering to provide this.

However if you want to use the full spectrum of web-forms then yes, you will need all these dependencies. This is why they are each in the suggest list of composer installations.

**Comment by Mech7** [comment]
Isn't rendering the forms what you would want pretty much always? I can't really think of another use case.
For validation there are other packages available.

**Comment by weierophinney** [comment]
@Mech7 — While you will likely only use zend-form if you will also be rendering the form, you might *not* be rendering it with the zend-view `PhpRenderer`, which is what @manuakasam is getting at. E.g., if you were integrating with Twig, or Mustache, or Plates, etc. In those cases, pulling in zend-view and its dependencies makes no sense.

Our policy is to define the minimal set of dependencies required, and suggest dependencies that are for any optional use cases, even if these are the _typical_ use case. In the future, we will likely do work to reduce dependencies, and move specific use cases — e.g., in this component, rendering via zend-view — into the framework package, the skeleton package, or "bridge" packages.
